name: Build iStoreOS‑Docker rootfs
on:
  workflow_dispatch: # 手动触发（网页点按钮运行）
  # push: # 取消注释，提交代码自动触发

jobs:
  build:
    runs-on: ubuntu‑22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install‑y tar zstd wget curl

      # ========== 示例编译x86_64，armsr同理复制一份 ==========
      - name: Download iStoreOS ImageBuilder x86_64
        run: |
          cd targets/x86_64
          # 替换为你需要版本的ib包，来自 https://fw.koolcenter.com/iStoreOS/ib/
          wget https://fw.koolcenter.com/iStoreOS/ib/istoreos‑imagebuilder‑x86‑64.tar.zst
          tar --zstd -xvf istoreos‑imagebuilder‑x86‑64.tar.zst

      - name: Run build.sh x86_64
        run: |
          cd targets/x86_64
          ./build.sh

      - name: Upload Artifact x86_64‑rootfs
        uses: actions/upload‑artifact@v4
        with:
          name: istoreos‑x86‑64‑rootfs
          path: targets/x86_64/bin/*.tar.gz

      # ----- arm64/armsr架构可复制上面步骤修改路径与ib文件名 -----
